### ISSUE TITLE
White Screen when debugging

### ISSUE THREAD

**Issue by hffmnn** [cbrevik/react-native-typescript-starter#1] opened 2017-05-30 14:24 UTC
Hi,

thanks a lot for your great post and this repository. 

When playing around with it I tried to start debugging via VS Code, but the iOS simulator presented me a white screen. When debugging via Chrome DevTools I had no problem at all.

Because you wrote, that you are also using VS Code: Did you have any similar problems?

Thanks and regards,
Christian

**Comment by cbrevik** [comment] 2017-05-31 06:05
Hi @hffmnn,

I don't normally use VS Code to debug my RN apps, I prefer the Chrome debugger. I normally have less trouble with it.

I tried to run the app with the following `configurations` in my `launch.json`:
```json
    "configurations": [
        {
            "name": "Debug iOS",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "sourceMaps": true,
            "target": "iPhone 5s",
            "outDir": "${workspaceRoot}/.vscode/.react"
        }
    ]
```

And that worked fine for me, no white screen.

Almost sounds like the same problem I've had earlier when messing around with my `tsconfig.json` settings though. What helped then was resetting the cache with `yarn start -- --reset-cache` in the project root. Maybe that clears it up?

**Comment by hffmnn** [comment] 2017-06-01 12:33
Hi @cbrevik,

thanks for all the tips, but looks like it does not work over here. As soon as I start debugging in VS Code, it does not work (white screen of dead if you will).

I guess I should open a issue at https://github.com/Microsoft/vscode-react-native so that this issue can be closed?

**Comment by hffmnn** [comment] 2017-06-08 09:35
Not created by me, but still useful for reference:
https://github.com/Microsoft/vscode-react-native/issues/459

**Comment by cbrevik** [comment] 2017-06-09 18:05
Hi sorry I've been unresponsive here. I've been very busy lately. 

This is probably an issue with the packager running via VSCode, and thus is to do with the extension you're linking yeah. I see now I'm not getting break points inside VSCode with TypeScript. So that probably needs some work, but I'm not sure if it is a problem with the RN packager or the transformer itself.

I am unable to reproduce the white screen of death issue though.

**Comment by cristian-milea** [comment] 2017-06-09 22:23
i have the same problem. white screen when i debug with vscode.
if i run remote debug with chrome, it works ok.

**Comment by serayuzgur** [comment] 2017-06-24 11:09
Thansk for such a nice plugin. I got the same problem. Running packager via some custom scripts. Ok via chrome but snow white with vsc.

**Comment by vincent0225** [comment] 2017-07-01 16:04
I have the same problem.
The problem can be reproduced when debugging with iphone simulator and real device.
It works fine with android device.

**Comment by cbrevik** [comment] 2018-03-17 11:15
Seems like the issue reference earlier (https://github.com/Microsoft/vscode-react-native/issues/459) has been resolved. Is this still an issue for people?

I am unable to reproduce this so tempted to close this issue unless anyone is still experiencing this.

**Closed as completed** 2018-04-01 10:28 UTC
